"""empty message

Revision ID: 617c72368c39
Revises: 
Create Date: 2017-07-25 21:11:32.519152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617c72368c39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
